Failure # 1 (occurred at 2021-08-20_13-02-09)
Traceback (most recent call last):
  File "/home/patrick/.local/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 718, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/patrick/.local/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 688, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/patrick/.local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/home/patrick/.local/lib/python3.8/site-packages/ray/worker.py", line 1497, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::PPO.__init__()[39m (pid=25341, ip=192.168.0.74)
  File "python/ray/_raylet.pyx", line 501, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task.function_executor
  File "/home/patrick/.local/lib/python3.8/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/home/patrick/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 123, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/home/patrick/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 548, in __init__
    super().__init__(config, logger_creator)
  File "/home/patrick/.local/lib/python3.8/site-packages/ray/tune/trainable.py", line 98, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/patrick/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 709, in setup
    self._init(self.config, self.env_creator)
  File "/home/patrick/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py", line 150, in _init
    self.workers = self._make_workers(
  File "/home/patrick/.local/lib/python3.8/site-packages/ray/rllib/agents/trainer.py", line 791, in _make_workers
    return WorkerSet(
  File "/home/patrick/.local/lib/python3.8/site-packages/ray/rllib/evaluation/worker_set.py", line 81, in __init__
    remote_spaces = ray.get(self.remote_workers(
  File "/home/patrick/.local/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::RolloutWorker.__init__()[39m (pid=25344, ip=192.168.0.74)
  File "python/ray/_raylet.pyx", line 501, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task.function_executor
  File "/home/patrick/.local/lib/python3.8/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/home/patrick/.local/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 536, in __init__
    self.policy_map, self.preprocessors = self._build_policy_map(
  File "/home/patrick/.local/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1165, in _build_policy_map
    preprocessor = ModelCatalog.get_preprocessor_for_space(
  File "/home/patrick/.local/lib/python3.8/site-packages/ray/rllib/models/catalog.py", line 706, in get_preprocessor_for_space
    cls = get_preprocessor(observation_space)
  File "/home/patrick/.local/lib/python3.8/site-packages/ray/rllib/models/preprocessors.py", line 318, in get_preprocessor
    legacy_patch_shapes(space)
  File "/home/patrick/.local/lib/python3.8/site-packages/ray/rllib/models/preprocessors.py", line 356, in legacy_patch_shapes
    return space.shape
AttributeError: 'str' object has no attribute 'shape'

